### ISSUE TITLE
TransformJ increases image resolution by 1 pixel

### ISSUE THREAD

**Issue by akatav** [imagescience/TransformJ#5]
@emeijering @ctrueden 
I am using TransformJ on a set of 2d images that were previously corrected for rigid registration using StackReg.Each 2d image is 512 by 512.After applying transformJ affine using the corresponding transformation matrix for a specific image, the image resolution changes to 513*513.But i'd like to have the same image resolution if possible.
I have attached a sample image and it's transformation matrix for illustration purposes. 

[file3.txt](https://github.com/imagescience/TransformJ/files/4337127/file3.txt)

![3](https://user-images.githubusercontent.com/721570/76739373-73535400-67af-11ea-88f5-edea650111e5.jpg)

Would it be correct to adjust the resolution of the final images back to 512 by 512 ?

**Comment by emeijering** [comment]
Deselecting the "Adjust bounds to fit result" option should solve the problem.

**Comment by akatav** [comment]
@emeijering thank you. 
We have images from 3 channels acquired from the same FOV. After using StackReg to register images of a reference channel and get the transformation matrices, TransformJ is used to transform images of the other 2 channels.However, some frames returned by StackReg are zero padded. Like below: 
![ch29](https://user-images.githubusercontent.com/721570/76824006-27f58000-6859-11ea-9e27-b876a36661b3.jpg)

This zero padding affects the alignment between the reference and candidate channel after using TransformJ.How can this be resolved?

**Comment by emeijering** [comment]
This does not sound like a problem with TransformJ but with StackReg? Perhaps you can ask the authors of StackReg how to solve the issue with zero padding.
